name: psycho
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/thumbnail/
    - images/
    - images/thumbnail/
    # - images/test_thumbnail/1/_5ffa8355-8f86-451e-8383-987877284fcd.jpeg
    # - images/test_thumbnail/2/_bf398619-e3f6-450d-93f8-2ff04398fbf5.jpeg
