name: psycho
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  in_app_review: ^2.0.8
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  lottie: ^3.0.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - images/thumbnail/
    - assets/crying.json
    - assets/making.json
    # - images/test_thumbnail/1/_5ffa8355-8f86-451e-8383-987877284fcd.jpeg
    # - images/test_thumbnail/2/_bf398619-e3f6-450d-93f8-2ff04398fbf5.jpeg
